# ==================== PROTEIN SEQUENCES FROM EXAMPLES ====================
# These sequences are used in various examples from the README

# PDL1 protein sequence - used in examples 1, 2, 3, 4, 5, 7
EXAMPLE_PDL1_SEQUENCE = "AFTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNIIQFVHGEEDLKVQHSSYRQRARLLKDQLSLGNAALQITDVKLQDAGVYRCMISYGGADYKRITVKVNAPYAAALE"

# Shorter PDL1 variant - used in example 2 (template example)
EXAMPLE_PDL1_SHORT_SEQUENCE = "FTVTVPKDLYVVEYGSNMTIECKFPVEKQLDLAALIVYWEMEDKNIIQFVHGEEDLKVQHSSYRQRARLLKDQLSLGNAALQITDVKLQDAGVYRCMISYGGADYKRITVKVNK"

# Multimer protein sequence - used in example 4 (1GNW dimer)
EXAMPLE_MULTIMER_SEQUENCE = "AGIKVFGHPASIATRRVLIALHEKNLDFELVHVELKDGEHKKEPFLSRNPFGQVPAFEDGDLKLFESRAITQYIAHRYENQGTNLLQTDSKNISQYAIMAIGMQVEDHQFDPVASKLAFEQIFKSIYGLTTDEAVVAEEEAKLAKVLDVYEARLKEFKYLAGETFTLTDLHHIPAIQYLLGTPTKKLFTERPRVNEWVAEITKRPASEKVQ"

# RNA sequence - used in example 6
EXAMPLE_RNA_SEQUENCE = "AGAGAGAGA"

# Longer RNA sequence - used in nucleic acid binding example
EXAMPLE_RNA_LONG_SEQUENCE = "AGAGAGA"

# Small molecule ligand CCD code - used in example 5
EXAMPLE_LIGAND_SAM = "SAM"

# SMILES string for ligand binder design (Chai example)
EXAMPLE_LIGAND_SMILES = "O=C(NCc1cocn1)c1cnn(C)c1C(=O)Nc1ccn2cc(nc2n1)c1ccccc1"

# Generic target sequence (20 amino acids) - Chai unconditional design
EXAMPLE_GENERIC_TARGET = "ACDEFGHIKLMNPQRSTVWY"